
let express = require('express');
const { socket } = require('server/router');
const app=express()
const server=require('http').createServer(app)
const io=require('socket.io')(server,{cors:{origin:"*"}})
//This code includes the 'socket' module from the 'server/router' package, sets up an Express application, 
//creates an HTTP server, and initializes Socket.IO with the server, allowing CORS from any origin.


app.set('view engine','ejs')


app.get('/home',(req,res)=>{
  res.render('home')
  //This code sets up a route for the GET request to the '/home' URL path. When a request is made to this path, 
  //it renders and sends the 'home' view or template as a response to the client. The 'home' view could be an HTML
  // page or a dynamic template generated by a view engine.
})

server.listen(8000,()=>{
  console.log("Server Running......")
  //This code instructs the server to listen on port 8000 for incoming connections.
  // Once the server is successfully listening, it logs a message "Server Running......" to the console.
})

io.on('Connection',(socket)=>{
  console.log("User connected", + socket.id)
  socket.on("message",(data)=>{
    socket.broadcast.emit("message",data)
  })

})
//This code listens for a 'Connection' event on the Socket.IO server. When a user connects, it logs a message with the user's socket ID. 
//It also listens for 'message' events from the user and broadcasts the received message to all connected clients except the sender.


